version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.production
    image: dockerlized-bff-prod
    links:
      - db
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./bin/www
  db:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db