version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.development
    image: dockerlized-bff-dev
    links:
      - db
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/app
    command: npm run debug
  web-unit-test:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.test
    image: dockerlized-bff-test
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run ut
  web-integration-test:
    image: dockerlized-bff-test
    links:
      - db-test
    depends_on:
      - web-unit-test
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
    command: npm run it
  db:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data.db
  db-test:
    image: mongo:3.4.4
    tmpfs: /data/db