version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.development
    image: dockerlized-bff-dev
    links:
      - db
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
      - "5858:5858"
    volumes:
      - .:/app
    command: npm run debug
  db:
    image: mongo:3.4.4
    ports:
      - "27017:27017"
    volumes:
      - ./db:/data/db