version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.development
    image: dockerlized-bff:dev
    links:
      - db
      - db-test
    environment:
      NODE_ENV: development
    ports:
      - "3010:3000"
      - "5858:5858"
    volumes:
      - .:/app
    command: yarn docker-command:dev
  db:
    image: mongo:3.4.4
    ports:
      - "27117:27017"
    volumes:
      - ./db:/data/db
  db-test:
    image: mongo:3.4.4
    ports:
      - "27118:27017"
    tmpfs: /data/db