version: "3"
services:
  web-production:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.production
    image: dockerlized-bff:prod
    links:
      - db-production:db
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8180:8080"
    volumes:
      - .:/app
    command: ./bin/www
  db-production:
    image: mongo:3.4.4
    ports:
      - "28017:27017"
    volumes:
      - ./db:/data/db