version: "3"
services:
  web:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.production
    image: web
    environment:
      NODE_ENV: production
      PORT: 8080
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: ./bin/www