version: "3"
services:
  web_unit_test:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.test
    image: dockerlized-bff:unit-test
    environment:
      NODE_ENV: development
    command: npm run ut-ci
  web_integration_test:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.test
    image: dockerlized-bff:integration-test
    links:
      - db_test
    environment:
      NODE_ENV: development
    command: npm run it-ci
  db_test:
    image: mongo:3.4.4
    tmpfs: /data/db