version: "3"
services:
  web-unit-test:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.integration
    image: dockerized-bff:unit-test
    command: yarn ut-ci
  web-integration-test:
    build:
      context: .
      dockerfile: ./dockerfiles/Dockerfile.integration
    image: dockerized-bff:integration-test
    links:
      - db
    command: yarn it-ci
  db:
    image: mongo:3.4.4
    tmpfs: /data/db