FROM node:6.10.3-alpine

WORKDIR /app

RUN yarn config set registry https://registry.npm.taobao.org

ENV NODE_ENV=production

COPY package.json yarn.lock /app/
RUN yarn
RUN mv /app/node_modules /node_modules

COPY . /app

CMD ["./bin/www"]